travis:
  secure:
    BINSTAR_TOKEN: nRVH9/tC4Mtby0BUw3ydiVqtLLzHQVJGfrNoIXiHk6YI/E+86Tmh6yga6I15XZpujF/5S+AePko+XYTf9L2zsmLHLmjyeEy49Ag6UjSR+hDuIiagyABA+0dOnCIn5Diohi/zNcAjKZSvQFHBDs5pH85y8DuX5TTNW2NGPVGpNiOKDIRucIG92EtXn6zkAu5LrcFrv+6TN53B7wGUl/sDnftINGJ4CKKE9v9sVAPoOgiKcXHfo0txrYwdDCo9WWV9pNMlT9wyHyIb1MdkZfGEB82r+yohSBmFM3Nprm17tNm/GtxP6psmqqf1E8C/tzy4WTKJBdt/KjlEM0m/IM5Xgd3kVcVmbTyUANlwz4QL6Grqw6609vfzhHeEiOkyjpcavJ32paYLvmHHLZvwXBfIZ4qxy4+cWwQUxw1SWpAVMYugj6YzNp5bSSWVIwLOL76b1IKBvX3DWIJkFrqNap1M0fZLJ6ftn4z1SKOPyEi/Z8gfcqZ5bkrFiESs8OpKdwVtFPGTbbk0wSHb6cl7FlCMK5XgFc7JUE2Leswf4UGcs4Jy7Ix8nFauzi9q1aEt4E60dmUfug2X4KzMlE0kjepSR7S3MzhWcTG/lJa/KT7NC/IDNtTaEYnMV9abj5w5kmdG/mhJhrBzDbTX1SjghG+rrhAgJAtMKcLdPhTjIKOiMLU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
